{{- range $key, $value := .Values.overlays }}
{{- if and (eq .type "secrets") (eq (default $.Values.app.env .env) $.Values.app.env) }}
  {{- $scope := mustMergeOverwrite (deepCopy .) $ (dict "scope" $key) }}
  {{- $app_name := include "kubecraft.app-fullname" $scope }}
  {{- $template_name := ternary "%s" "%s-env-vars" (kindIs "string" .fullname) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf $template_name $app_name }}
  namespace: {{ $.Release.Namespace }}
type: Opaque
data:
  {{- $items := dict }}
  {{- range $k, $v := .items }}
    {{- if hasSuffix ":plain" $k }}
      {{- $items := set $items (trimSuffix ":plain" $k) (b64enc $v) }}
    {{- else }}
      {{- $items := set $items $k $v }}
    {{- end }}
  {{- end }}
  {{- $items | toYaml | nindent 2 }}
{{- end }}
{{- end }}
