---
# Source: kubecraft/templates/poddisruptionbudget.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: external-config-consumer-api-pdb
  namespace: default
spec:
  minAvailable: 100%
  selector:
    matchLabels:
      app/name: external-config-consumer-api
      app/subset: main
---
# Source: kubecraft/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: external-config-consumer-api
  namespace: default
spec:
  type: ClusterIP
  selector:
    app/name: external-config-consumer-api
    app/subset: main
---
# Source: kubecraft/templates/daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app/name: external-config-consumer-node-agent
    app/realm: sandbox
    app/subset: main
  name: external-config-consumer-node-agent
  namespace: default
spec:
  selector:
    matchLabels:
      app/name: external-config-consumer-node-agent
      app/subset: main
  template:    
    metadata:
      labels:
        app/name: external-config-consumer-node-agent
        app/realm: sandbox
        app/subset: main
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - sleep infinity
        env:
        - name: REALM_CONTEXT_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app/realm']
        image: docker.io/busybox:latest
        name: app
        volumeMounts:
        - mountPath: /app/config
          name: external-config
          readOnly: true
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: application.yaml
            path: application.yaml
          - key: logback.xml
            path: logging/logback.xml
          name: platform-runtime-config
        name: external-config
---
# Source: kubecraft/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app/name: external-config-consumer-api
    app/realm: sandbox
    app/subset: main
  name: external-config-consumer-api
  namespace: default
spec:
  selector:
    matchLabels:
      app/name: external-config-consumer-api
      app/subset: main
  template:    
    metadata:
      labels:
        app/name: external-config-consumer-api
        app/realm: sandbox
        app/subset: main
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - sleep infinity
        env:
        - name: REALM_CONTEXT_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app/realm']
        image: docker.io/busybox:latest
        name: app
        volumeMounts:
        - mountPath: /app/config
          name: external-config
          readOnly: true
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: application.yaml
            path: application.yaml
          - key: logback.xml
            path: logging/logback.xml
          name: platform-runtime-config
        name: external-config
---
# Source: kubecraft/templates/cronjob.yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app/name: external-config-consumer-snapshot
    app/realm: sandbox
    app/subset: main
  name: external-config-consumer-snapshot
  namespace: default
spec:
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        metadata:
          labels:
            app/name: external-config-consumer-snapshot
            app/realm: sandbox
            app/subset: main
        spec:
          containers:
          - command:
            - /bin/sh
            - -c
            - cat /app/config/application.yaml
            env:
            - name: REALM_CONTEXT_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app/realm']
            image: docker.io/busybox:latest
            name: app
            volumeMounts:
            - mountPath: /app/config
              name: external-config
              readOnly: true
          restartPolicy: OnFailure
          volumes:
          - configMap:
              defaultMode: 420
              items:
              - key: application.yaml
                path: application.yaml
              - key: logback.xml
                path: logging/logback.xml
              name: platform-runtime-config
            name: external-config
