app:
  subset: main
  env: sandbox

overlays:
  k8s-management:
    type: rbac
    clusterRole: true
    rules:
    - apiGroups: ["apps"]
      resources: ["deployments"]
      verbs: ["get", "patch"]

workloads:
  demo:
    enabled: true
    operation: worker
    image: bitnami/kubectl:latest
    command: [ sleep, infinity ]
    containerExtras:
      app:
        imagePullPolicy: IfNotPresent
    overlays:
    - k8s-management

