{{- range $key, $value := .Values.overlays }}
{{- if eq .type "env-vars" }}
  {{- $scope := mustMergeOverwrite (deepCopy .) $ (dict "scope" $key) }}
  {{- $app_name := include "kubecraft.app-fullname" $scope }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-env-vars" $app_name }}
  namespace: {{ include "kubecraft.app-namespace" $ }}
data:
  {{- range $env_key, $env_value := .items }}
    {{- if not (or (kindIs "map" $env_value) (regexMatch "\\$\\([\\w]+\\)" $env_value) ) }}
  {{ $env_key }}: {{ $env_value | quote }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
