{{- range $key, $value := .Values.workloads }}
{{- if and .enabled (has (default $key .operation) (list "agent" "daemon" "daemonset")) }}
  {{- $scope := mustMergeOverwrite (deepCopy .) $ (dict "scope" $key) }}
  {{- $app_name := include "kubecraft.app-fullname" $scope }}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  {{- $labels := include "kubecraft.metadata-labels" $scope | fromYaml }}
  {{- $metadataExtras := get (.extras | default dict) "metadata" | default dict }}
  {{- mustMergeOverwrite (deepCopy $metadataExtras) $labels (dict "name" $app_name "namespace" $.Release.Namespace) | toYaml | nindent 2 }}
spec:
  selector:
    matchLabels:
      app/name: {{ $app_name }}
      app/subset: {{ $.Values.app.subset }}
  {{- $specExtras := get (.extras | default dict) "spec" | default dict }}
  {{- $specExtras := unset $specExtras "selector"}}
  {{- if $specExtras }}
    {{- $specExtras | toYaml | nindent 2 }}
  {{- end }}
  template:
  {{- include "kubecraft.pod-template" $scope | indent 4 }}
{{- end }}
{{- end }}
