{{- range $key, $value := .Values.workloads }}
{{- if and .enabled (has (default $key .operation) (list "api" "service" "stream" "worker")) }}
  {{- $scope := mustMergeOverwrite (deepCopy .) $ (dict "scope" $key) }}
  {{- $app_name := include "kubecraft.app-fullname" $scope }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $app_name }}
  namespace: {{ include "kubecraft.app-namespace" $ }}
  labels:
    app/name: {{ $app_name }}
    app/realm: {{ $.Values.app.env }}
spec:
  selector:
    matchLabels:
      app/name: {{ $app_name }}
  {{- if .maxSurge }}
  strategy:
    rollingUpdate:
      maxSurge: {{ .maxSurge }}
      maxUnavailable: 0
    type: RollingUpdate
  {{- end }}
  template:
  {{- include "kubecraft.pod-template" $scope | indent 4 }}
{{- end }}
{{- end }}
