{{- range $key, $value := .Values.workloads }}
{{- if and .enabled (has (default $key .operation) (list "api" "service" "stream" "worker")) }}
  {{- $scope := mustMergeOverwrite (deepCopy .) $ (dict "scope" $key) }}
  {{- $app_name := include "kubecraft.app-fullname" $scope }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ $app_name }}-pdb
  namespace: {{ $.Release.Namespace }}
spec:
  minAvailable: 100%
  selector:
    matchLabels:
      app/name: {{ $app_name }}
      app/subset: {{ $.Values.app.subset }}
{{- end }}
{{- end }}
