{{- range $key, $value := .Values.overlays }}
{{- if and (eq .type "rbac") (eq $.Values.app.subset "main") (eq (default $.Values.app.env .env) $.Values.app.env) }}
  {{- $scope := mustMergeOverwrite (deepCopy .) $ (dict "scope" $key) }}
  {{- $sa_name := include "kubecraft.app-fullname" $scope }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ ternary "ClusterRole" "Role" (default false .clusterRole) }}
metadata:
  name: {{ printf "%s-rules" $sa_name }}
  {{- if not .clusterRole }}
  namespace: {{ $.Release.Namespace }}
  {{- end }}
rules:
  {{- .rules | toYaml | nindent 0 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ ternary "ClusterRoleBinding" "RoleBinding" (default false .clusterRole) }}
metadata:
  name: {{ $sa_name }}
  {{- if not .clusterRole }}
  namespace: {{ $.Release.Namespace }}
  {{- end }}
subjects:
- kind: ServiceAccount
  name: {{ $sa_name }}
  namespace: {{ $.Release.Namespace }}
roleRef:
  kind: {{ ternary "ClusterRole" "Role" (default false .clusterRole) }}
  name: {{ printf "%s-rules" $sa_name }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $sa_name }}
  namespace: {{ $.Release.Namespace }}
{{- end }}
{{- end }}
