{{- range $key, $value := .Values.overlays }}
{{- if and (eq .type "volume") (not .hostPath) (not .fromSecretRef) .secret (kindIs "map" .items) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-files" (.fullname | default $key | trimSuffix "-files") }}
  namespace: {{ $.Release.Namespace }}
data:
  {{- $items := dict }}
  {{- range $k, $v := .items }}
    {{- if hasSuffix ":plain" $k }}
      {{- $items := set $items (trimSuffix ":plain" $k) (b64enc $v) }}
    {{- else }}
      {{- $items := set $items $k $v }}
    {{- end }}
  {{- end }}
  {{- $items | toYaml | nindent 2 }}
{{- end }}
{{- end }}
