{{- range $key, $value := .Values.workloads }}
{{- if and .enabled (has (default $key .operation) (list "api" "service")) }}
  {{- $scope := mustMergeOverwrite (deepCopy .) $ (dict "scope" $key) }}
  {{- $app_name := include "kubecraft.app-fullname" $scope }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $app_name }}
  namespace: {{ $.Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app/name: {{ $app_name }}
    app/subset: {{ $.Values.app.subset }}
  {{- if .servicePorts }}
  ports:
    {{- range $portName, $portValue := .servicePorts }}
  - name: {{ regexReplaceAll "/[^/]+$" $portName "" }}
    protocol: {{ ternary "UDP" "TCP" (hasSuffix "/UDP" $portName) }}
    port: {{ $portValue }}
    targetPort: {{ $portValue }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
